# This is for testing purpose, will be removevd and implement with helm chart for deployments

version: '3'

services:
  postgres:
    image: postgres
    container_name: scrapper_db
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: